# Generated by Django 5.1.3 on 2024-11-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotografira',
            new_name='Fotografia',
        ),
    ]
